jwpconsulting/projectify

projectify/settings/base.py, todo/schema.py, user/schema.py
=> Resolve pytest warnings

Pipfile.lock, projectify/settings/production.py
=> Settings/Production: Add CORS origins

projectify/settings/development.py, projectify/settings/production.py, projectify/settings/test.py, projectify/urls.py, projectify/views.py
=> Enable batching

workspace/models.py, workspace/schema.py, workspace/test/test_models.py
=> Workspace: Add uuid retrieval for fields

projectify/settings/base.py, projectify/settings/production.py
=> Cors middleware

projectify/templates/email/_greeting.txt, user/emails.py, user/models.py, user/schema.py, user/templates/user/email/password_reset_body.txt, user/templates/user/email/password_reset_subject.txt, user/test/test_emails.py, user/test/test_schema.py
=> Password reset

Pipfile, Pipfile.lock, Procfile, projectify/asgi.py, projectify/schema.py, projectify/settings/base.py, projectify/settings/development.py, projectify/settings/production.py, projectify/settings/test.py, projectify/wsgi.py, workspace/apps.py, workspace/schema.py, workspace/signals.py
=> Initial ASGI support + gql sub

workspace/test/test_schema.py
=> Sub task mutation

projectify/settings/production.py
=> Production: Limit celery workers to one

projectify/settings/production.py
=> Production: Change celery configuration key

Procfile, projectify/settings/production.py
=> Production: Limit celery worker to one process & force SSL redirect

projectify/settings/production.py
This reverts commit dfc43a0d6f8410df0c6695741f272474bf2dbb8c.
=> Revert "Production: Change celery configuration key"

projectify/middleware.py, projectify/settings/base.py
=> Projectify: Make gql queries atomic

workspace/models.py, workspace/schema/mutation.py, workspace/schema/types.py, workspace/test/test_models.py, workspace/test/test_schema.py
=> Make sections movable

workspace/schema/loader.py, workspace/schema/mutation.py, workspace/test/test_schema.py
=> Update workspace board mutation

Procfile, gunicorn-error.log
=> Production: Suppress date on gunicorn logs

workspace/schema/mutation.py, workspace/test/test_schema.py
=> Workspace: Add delete mutations and tests

Pipfile, Pipfile.lock, projectify/asgi.py, projectify/urls.py, pyproject.toml, pytest.ini, workspace/consumers.py, workspace/schema/subscription.py, workspace/signals.py, workspace/test/test_consumers.py
This websocket consumer returns the uuid of a workspace everytime an object within it changes
=> Add websocket consumer for save signal processing

workspace/schema/mutation.py, workspace/test/test_schema.py
=> Workspace: Add update mut

projectify/middleware.py
=> Projectify/Middleware: Run only once

conftest.py, user/test/test_schema.py, workspace/test/test_schema.py
=> Make graphql_user return json directly

workspace/signals.py, workspace/test/test_consumers.py
=> Workspace/Consumers: Track workspace user changes

projectify/settings/base.py
=> Gzip middleware

workspace/models.py, workspace/schema/types.py, workspace/test/test_models.py
=> Workspace: Add next section getter

user/schema.py
=> User/Schema: Check if logged in

workspace/models.py, workspace/schema/mutation.py, workspace/test/schema/test_mutation.py, workspace/test/test_models.py
=> Duplicate task

workspace/signals.py, workspace/test/test_consumers.py
=> Workspace: fire signal on delete

projectify/management/commands/seeddb.py, workspace/admin.py
=> Seeddb and admin improvements

projectify/settings/production.py
This reverts commit 08ccceb81f491b1fc3d8a3a2c2f716cf93c9a1ac.
=> Settings/Production: Try fixing channels redis

projectify/settings/base.py, projectify/settings/development.py, projectify/settings/production.py, projectify/settings/test.py
I forgot that it needs to be set for staticfiles as well
=> Fix STORAGES configuration

workspace/signals.py
Turns out you can apply multiple decorators to the same method!
=> Workspace: Merge signal handlers

workspace/rules.py
We would only look at the trial state during create, but never during the other ones, so that got us in trouble.
=> Workspace: Correctly respect trial limits

flake.nix
Set to same version as in CircleCI config
=> Fix postgres version in flake.nix

README.md, flake.nix, user/models/user.py, user/services/user.py
Clean up user model and make nix flake shell work on macOS with nix-darwin.
=> Lay groundwork for password change

backend/README.md, backend/flake.nix, backend/poetry.lock, backend/projectify/workspace/test/models/test_task.py, backend/projectify/workspace/test/models/test_workspace.py, backend/pyproject.toml, backend/requirements.txt
1. Update README with quickstart instructions
2. Update psycopg
3. Make flake nix build inputs and poetryenv variables explicit
=> Add minor tweaks to backend

frontend/.eslintrc.cjs, frontend/package-lock.json, frontend/package.json, frontend/src/bin/check-i18n.ts, frontend/src/lib/components/help/Layout.svelte, frontend/src/messages/en.ts, frontend/src/routes/(storefront)/help/(page)/basics/+page.svelte, frontend/src/routes/(storefront)/help/(page)/billing/+page.svelte, frontend/src/routes/(storefront)/help/(page)/filters/+page.svelte, frontend/src/routes/(storefront)/help/(page)/labels/+page.svelte, frontend/src/routes/(storefront)/help/(page)/quota/+page.svelte, frontend/src/routes/(storefront)/help/(page)/tasks/+page.svelte, frontend/src/routes/(storefront)/help/(page)/trial/+page.svelte, frontend/src/routes/(storefront)/help/(page)/workspace-board-sections/+page.svelte, frontend/src/routes/(storefront)/help/(page)/workspace-boards/+page.svelte, frontend/src/routes/(storefront)/help/(page)/workspace-users/+page.svelte, frontend/src/routes/(storefront)/help/(page)/workspaces/+page.svelte, frontend/src/routes/(storefront)/help/+page.svelte
=> Continue improving help pages

backend/projectify/user/models/user_invite.py, backend/projectify/workspace/serializers/workspace.py, backend/projectify/workspace/services/workspace_user_invite.py, backend/projectify/workspace/test/services/test_workspace_user_invite.py, backend/projectify/workspace/test/test_consumers.py, backend/projectify/workspace/test/views/test_workspace.py, frontend/src/lib/types/workspace.ts, frontend/src/routes/(platform)/dashboard/workspace/[workspaceUuid]/settings/billing/+page.svelte, frontend/src/routes/(platform)/dashboard/workspace/[workspaceUuid]/settings/workspace-users/+page.svelte
- Add thorough test to entire invite life cycle
- Add "invited" date display
- Fix issue with billing portal navigation being broken after sveltekit update
- Add "X" icon to remove button in invite row
=> Finish ws user invite management

backend/projectify/corporate/selectors/customer.py, backend/projectify/corporate/services/stripe.py, backend/projectify/corporate/test/services/test_stripe.py, backend/projectify/corporate/test/views/test_customer.py, backend/projectify/corporate/views/customer.py
This is in preparation for a bug fix
=> Refactor corporate app code a bit

backend/mypy/stubs/rest_framework/decorators.pyi, backend/projectify/conftest.py, backend/projectify/corporate/models/customer.py, backend/projectify/corporate/serializers.py, backend/projectify/corporate/services/customer.py, backend/projectify/corporate/services/stripe.py, backend/projectify/corporate/test/conftest.py, backend/projectify/corporate/test/models/test_customer.py, backend/projectify/corporate/test/services/test_stripe.py, backend/projectify/corporate/test/views/test_customer.py, backend/projectify/corporate/test/views/test_stripe.py, backend/projectify/corporate/views/stripe.py, backend/projectify/workspace/test/conftest.py, backend/projectify/workspace/test/test_consumers.py, backend/projectify/workspace/test/views/test_task.py, docs/backend/stripe.md, frontend/src/lib/storybook.ts, frontend/src/lib/types/corporate.ts, frontend/src/messages/en.ts, frontend/src/routes/(platform)/dashboard/workspace/[workspaceUuid]/settings/billing/+page.svelte
- Add redirect URLs
- Handle more webhooks
- Make webhooks very very type safe
- Do a round of testing with the local stripe clients and try to handle as many edge cases as possible
- Handle failed/cancelled subscriptions better.
=> Fix stripe issues

backend/projectify/user/test/test_emails.py
Previously, we created the user email confirm token a second time and check if it is part of the email. If user_make_token, and email rendering do not happen within the same second, the token will be different. CircleCI pointed out that this test was flaky.
I have done the same for the user password reset email.
=> BE: Fix flaky user email tests

frontend/src/lib/figma/buttons/ContextMenuButton.svelte, frontend/src/lib/figma/navigation/side-nav/FilterLabels.svelte, frontend/src/lib/figma/navigation/side-nav/Full.svelte
Somehow, wrapping everything in too many <div>s with overflow-* or shrink messed it up. Removing the div containers until a better solution for overflow is found.
=> Fix broken focus ring in side nav label create button

frontend/src/lib/components/ContextMenuContainer.svelte, frontend/src/lib/figma/navigation/side-nav/FilterTeamMembers.svelte, frontend/src/lib/figma/navigation/side-nav/Projects.svelte, frontend/src/lib/figma/overlays/MobileMenu.svelte, frontend/src/lib/figma/overlays/MobileMenuOverlay.svelte, frontend/src/lib/utils/scroll.ts, frontend/src/routes/(platform)/+layout.svelte, frontend/src/routes/(platform)/dashboard/project/[projectUuid]/+layout.svelte, frontend/src/routes/(storefront)/privacy/+page.svelte, frontend/src/routes/(storefront)/tos/+page.svelte, frontend/src/stories/figma/overlays/ContextMenuTest.svelte, frontend/vite.config.ts
- Clean up use of overflow-y-auto, this fixes many issues with overflow on small screens
- Fix context menu behavior when scrolling, this fixes many issues with scroll bars
=> Fix overflow issues

backend/projectify/workspace/test/views/test_project.py, backend/projectify/workspace/views/project.py, frontend/src/lib/stores/httpSubscription.ts, frontend/src/routes/(platform)/dashboard/+page.ts, frontend/src/routes/(platform)/dashboard/project/[projectUuid]/+layout.svelte, frontend/src/routes/(platform)/dashboard/project/[projectUuid]/+layout.ts, frontend/src/routes/(platform)/dashboard/project/[projectUuid]/+page.svelte, frontend/src/routes/(platform)/dashboard/project/[projectUuid]/search/+page.svelte, frontend/src/routes/(platform)/dashboard/project/[projectUuid]/search/+page.ts, frontend/src/routes/(platform)/dashboard/workspace/[workspaceUuid]/archive/+page.svelte
- Improve speed of archive response
- Render partial dashboard
- Fix issue where archive was unarchived twice by mistake in frontend
=> Fix performance issues in dashboard

frontend/src/lib/components/onboarding/DashboardPlaceholder.svelte, frontend/src/lib/types/workspace.ts, frontend/src/messages/en.ts, frontend/src/routes/(platform)/+layout.ts, frontend/src/routes/(platform)/dashboard/project/[projectUuid]/+page.svelte, frontend/src/routes/(platform)/dashboard/task/[taskUuid]/+layout.svelte, frontend/src/routes/(platform)/dashboard/task/[taskUuid]/+layout.ts, frontend/src/routes/(platform)/dashboard/task/[taskUuid]/+page.svelte, frontend/src/routes/(platform)/dashboard/task/[taskUuid]/update/+page.svelte, frontend/src/routes/+layout.ts
- Fix bug in onboarding placeholder rendering
- Fix issue where user was fetched twice
- Asynchronously load and display task page
=> Fix more performance issues

frontend/src/lib/figma/cards/task-card/TeamMember.svelte, frontend/src/lib/figma/navigation/AvatarVariant.svelte, frontend/src/lib/stores/wsSubscription.ts, frontend/src/routes/(platform)/dashboard/project/[projectUuid]/+page.svelte
- Fix missing console in production for sarus logging
- Fix avatar prop reload fail
- Remove some console.logs
=> Fix small issues

frontend/src/lib/figma/navigation/header/Dashboard.svelte, frontend/src/lib/figma/navigation/header/Layout.svelte, frontend/src/messages/en.ts, frontend/src/routes/(platform)/dashboard/workspace/[workspaceUuid]/settings/+page.svelte, frontend/src/routes/(platform)/user/profile/+page.svelte
- Warn before leaving profile/workspace settings form if not saved
- Redirect to dashboard when clicking poly logo
=> Add warning to forms when discarding changes, change dashboard top left logo behavior

backend/mypy/stubs/channels/security/websocket.pyi, backend/mypy/stubs/channels/testing.pyi, backend/projectify/asgi.py, backend/projectify/settings/test.py, backend/projectify/urls.py, backend/projectify/workspace/test/test_consumers.py
- Simplify consumer tests
- Properly test for 404 ws code if resource at uuid not found
- Validate Origin: HTTP Header properly
=> Improve websocket consumers

frontend/package-lock.json, frontend/package.json, frontend/src/routes/(storefront)/+page.svelte, frontend/src/routes/(storefront)/contact-us/+page.svelte, frontend/src/routes/+error.svelte, frontend/vite.config.ts
=> FE: Optimize some image assets

backend/poetry.lock, backend/requirements.txt
https://github.com/psf/requests/pull/6655
=> BE: Update requests

frontend/src/global.d.ts, frontend/src/lib/components/layouts/Hero.svelte, frontend/src/lib/components/solutions/SolutionsFeature.svelte, frontend/src/routes/(storefront)/+page.svelte, frontend/src/routes/(storefront)/accessibility/+page.svelte, frontend/src/routes/(storefront)/help/+page.svelte, frontend/src/routes/(storefront)/solutions/+page.svelte, frontend/src/routes/(storefront)/solutions/academic/+page.svelte, frontend/src/routes/(storefront)/solutions/development-teams/+page.svelte, frontend/src/routes/(storefront)/solutions/personal-use/+page.svelte, frontend/src/routes/(storefront)/solutions/project-management/+page.svelte, frontend/src/routes/(storefront)/solutions/remote-work/+page.svelte, frontend/src/routes/(storefront)/solutions/research/+page.svelte
The trick is to append ?enhanced to images
=> FE: Use enhanced:img more

backend/projectify/settings/base.py
See
https://docs.djangoproject.com/en/5.0/ref/middleware/#http-strict-transport-security
=> BE: Enable HSTS

frontend/src/lib/figma/composites/FilterLabelMenu.svelte
Make all labels filter always visible
=> FE: Fix FilterLabelMenu

docs/architecture.md, frontend/src/lib/figma/buttons/ContextMenuButton.svelte, frontend/src/lib/figma/composites/FilterTeamMember.svelte, frontend/src/lib/figma/navigation/Footer.svelte, frontend/src/lib/figma/navigation/side-nav/FilterTeamMembers.svelte, frontend/src/messages/en.ts, frontend/src/routes/(platform)/dashboard/project/[projectUuid]/search/+page.svelte
- Add link for team member settings to side nav
- Fixed the search layout, a regression after switching to gri
- Fix reference links in architecture docs
- Add a footer link to GitHub
=> Add a few little tweaks

AUTHORS.txt, README.md, frontend/src/lib/components/ContextMenuContainer.svelte, frontend/src/lib/figma/buttons/ContextMenuButton.svelte, frontend/src/lib/figma/overlays/context-menu/Task.svelte
Fixed context menu issues:
- Context menu was shown under browser's scrollbar.
- Context menu will have full screen width when clicking "Move to Section" button on task context menu. (If you have a long section title)
=> Fix context menu style

render.yaml
https://community.render.com/t/issue-connecting-my-container-to-minio/17424
=> Render: Fix docker -> image

Caddyfile, flake.nix, supervisord.conf
Again, this is to facilitate migration
=> Allow setting one more additional host in revproxy

frontend/svelte.config.js
This is not optimal, but we shall live with this for now
=> FE: Add unsafe-inline style-src CSP exception

Caddyfile
=> Revproxy: Fix typo in FE CSP fallback

flake.nix
Expose
- projectify-frontend-node
- projectify-manage
- projectify-backend
=> Expose sub-packages in flake

frontend/src/messages/en.ts
The column view was removed a while ago :/ Maybe I will add it back in one day?
=> Fix landing copy

docs/.prettierrc, docs/.prettierrc.license, docs/api_schema.md, docs/architecture.md, docs/backend/configuration.md, docs/backend/media-files.md, docs/backend/postgresql.md, docs/backend/rate-limiting.md, docs/backend/rest.md, docs/backend/services.md, docs/backend/stripe.md, docs/backend/traffic.md, docs/backend/unused-code.md, docs/containers.md, docs/frontend/api.md, docs/frontend/auth.md, docs/frontend/guide.md, docs/frontend/i18n.md, docs/frontend/layout.md, docs/frontend/onboarding.md, docs/frontend/urls.md, docs/password_policies.md, docs/rules.md, docs/supervisor.md, docs/text_replace.md, docs/trial.md
=> Prettify docs

backend/README.md, backend/poetry.lock, backend/pyproject.toml
- Updated dependencies in backend in response to Dependabot alerts
- [h11](https://github.com/jwpconsulting/projectify/security/dependabot/179)
- [gunicorn](https://github.com/jwpconsulting/projectify/security/dependabot/176)
- Django
- https://github.com/jwpconsulting/projectify/security/dependabot/177
- https://github.com/jwpconsulting/projectify/security/dependabot/175
- Updated README
- How to set setup Postgres on Mac
- Info on Django admin user
=> Update dependencies in backend

frontend/package-lock.json, frontend/package.json
- Updated dependencies in frontend in response to Dependabot alert
- [@svelte/kit](https://github.com/jwpconsulting/projectify/security/dependabot/178)
=> Update dependencies in frontend

backend/README.md, backend/projectify/settings/base.py, backend/projectify/storefront/templates/storefront/accessibility.html, backend/projectify/storefront/templates/storefront_base.html, backend/projectify/storefront/urls.py, backend/projectify/storefront/views.py, backend/projectify/urls.py
- Add dependency django-markdownify for accessibility page content
=> Add accessibility page

backend/projectify/settings/base.py, backend/projectify/settings/development.py, backend/projectify/storage.py
Document how we're going to use it in the future with the Django frontend.
=> BE: Update FRONTEND_URL settings
