- projectify/loader.py
- projectify/views.py
- workspace/schema/loader.py
- workspace/schema/types.py
- workspace/test/conftest.py
- workspace/test/test_schema.py
This fixes a problem where stale data would be served by already initialized data loaders leading to the UI showing old data. The issue was resolved by re-initializing the data loaders between each request. Drawback: Having to re-initialize all data loaders regardless of whether they are used or not could have a performance impact.
> Do not recycle data loaders between rqs

- projectify/graphql_ws_consumer.py
- projectify/middleware.py
- projectify/settings/base.py
- projectify/views.py
This initializes Loader() as part of middleware, not the view. This potentially allows us to populate loaders inside gql subscriptions as well. Unfortunately it is still broken, because now gql subscriptions don't return anything at all anymore. See https://github.com/datadvance/DjangoChannelsGraphqlWs/issues/91
> Projectify: Turn loader init into middleware

- Pipfile
- Pipfile.lock
No supported WebSocket library detected. Please use 'pip install
uvicorn[standard]', or install 'websockets' or 'wsproto' manually.
> Pipfile: Add websockets

- docs/rules.md
- frontend/src/lib/figma/screens/workspace-settings/TabBar.svelte
- frontend/src/lib/rules/workspace.ts
The tab bar item "billing" would be visible, even if a user did not have permission to access it. There would be a 403 error from the backend as well, since there it would fail the permission check if a user isn't owner of a workspace.
> Fix permission check on billing settings tab bar item

- frontend/src/lib/rules/workspace.ts
- frontend/src/lib/stores/dashboard/workspaceUser.ts
For example, when workspace_users_and_invites.can_create_more is false, the invite workspace user button will be hidden.
It would be better if there are two types of missing permission: 1) Privilege
2) Quota
For the second one it would be wise to show a disabled button instead of a hidden button.
> FE: Consider quotas for permission checks as well

- frontend/src/lib/figma/screens/workspace-settings/WorkspaceUserCard.svelte
- frontend/src/lib/stores/dashboard/task.ts
- frontend/src/messages/en.ts
- frontend/src/routes/(platform)/dashboard/workspace/[workspaceUuid]/settings/+page.svelte
- frontend/src/routes/(platform)/dashboard/workspace/[workspaceUuid]/settings/quota/+page.svelte
- Allow searching tasks by their section title
- Add instructions for how to request workspace deletion, since self-service delete is not supported right now.
- Disable workspace user remove button for own user, otherwise we'd get a 400 because the backend won't let you (also, removing yourself accidentally? yikes)
- Reactively update the ws quota page using ws subscription store
> Add small settings and dashboard tweaks

- frontend/src/lib/figma/cards/task-card/Labels.svelte
In task card, Label pill in assign mode would have different height because of border. Switch to using outline to have label pill in assign mode have same height as when labels are selected.
> FE: Fix issue with label pill height difference

- frontend/src/lib/components/OverlayContainer.svelte
- frontend/src/lib/figma/overlays/constructive/Layout.svelte
For reasons, the focus trap within a constructive overlay did not work well. It seems like removing the hidden submit button fixed the issue. (tested only in Firefox ESR in Debian 12...)
> Fix focus trap in constructive overlay

- backend/poetry.lock
- backend/pyproject.toml
- backend/requirements.txt
django-anymail used a deprecated Django API (django.utils.timezone.utc)
Updating to the new API was done in v9.0 released 2022-12-18 (ouch)
Update django-anymail to fix sending emails.
> BE: Update django-anymail to 10.3

- frontend/svelte.config.js
Out of an abundance of caution, I add two CSP directives that (mostly) prevent clickjacking.
Note that with prerendered pages frame-ancestors is ignored:
https://kit.svelte.dev/docs/configuration#csp
> FE: Add frame-src and frame-ancestors CSP

- netlify.toml
On top of SvelteKit's static pages only sometimes containing all specified csp <meta> tags, we also want to return a strict CSP header from Netlify, directly.
Regarding having multiple policies on the same page, the stricter one will be adopted by the browser, see:
https://w3c.github.io/webappsec-csp/#multiple-policies
> Netlify: Prevent clickjacking with CSP header

- backend/Procfile
- backend/bin/test-production-bootup
- backend/gunicorn.conf.py
Create a new gunicorn config file as specified in gunicorn docs. Use it in production startup test and Procfile (used in Heroku)
> Simplify gunicorn conf. / Procfile

- frontend/vite.config.ts
- Create sitemap after 'writeBundle' vite step finishes
- Use output in .svelte-kit/output/prerendered/pages for pages
> FE: Fix sitemap generation

- frontend/src/lib/components/help/Layout.svelte
- frontend/src/lib/components/layouts/HeroLayout.svelte
- frontend/src/lib/components/solutions/SolutionsPage.svelte
- frontend/src/lib/funabashi/buttons/HeaderButton.svelte
- frontend/src/routes/(onboarding)/+layout.ts
- frontend/src/routes/(platform)/+layout.ts
- frontend/src/routes/(storefront)/(auth)/+layout.ts
- frontend/src/routes/(storefront)/accessibility/+page.svelte
- frontend/src/routes/(storefront)/contact-us/+page.svelte
- frontend/src/routes/(storefront)/credits/+page.svelte
- frontend/src/routes/(storefront)/ethicalads/+page.svelte
- frontend/src/routes/(storefront)/free-software/+page.svelte
- frontend/src/routes/(storefront)/help/+page.svelte
- frontend/src/routes/(storefront)/privacy/+page.svelte
- frontend/src/routes/(storefront)/security/disclose/+page.svelte
- frontend/src/routes/(storefront)/security/general/+page.svelte
- frontend/src/routes/(storefront)/solutions/+page.svelte
- frontend/src/routes/(storefront)/tos/+page.svelte
- Enable SSR for more pages
- Fix weird CSS style flicker in landing hero
- Add landing page for ethical ads (which in turn just shows the original landing page at /)
> Add landing page for ethical ads, polish non-javascript loading experience

- backend/projectify/user/services/user.py
- backend/projectify/user/test/services/test_auth.py
- backend/projectify/user/test/services/test_user.py
- backend/projectify/user/views/user.py
- backend/schema/schema.yml
- frontend/src/lib/repository/user.ts
- frontend/src/lib/repository/util.ts
- frontend/src/lib/types/schema.d.ts
- frontend/src/routes/(platform)/user/profile/change-password/+page.svelte
Similar to sign up page,
- show password rules at the bottom of the form
- validate password in backend, and reject with "policies" error
- improve openapi schema to assist frontend type checking
- use openapi-fetch library for request
- add middleware to openapi-fetch in order to include csrftoken
- show new validation error in frontend if password rejected
> Perform password validation during password change as well

- frontend/flake.nix
- revproxy/.envrc
- revproxy/flake.lock
- revproxy/flake.nix
- supervisor/flake.lock
- supervisor/flake.nix
- supervisor/supervisord.conf
This allows us to launch frontend, using adapter-node, and projectify-revproxy (which in turns wraps Caddy) with one command each.
> Statically build frontend and revproxy

- backend/projectify/settings/production.py
- docs/backend/configuration.md
Important: If an API is served from a subdomain like "api.example.com", and frontend is accessible from "example.com", then CSRF_COOKIE_DOMAIN needs to be set to ".example.om" (note the extra `.` in the beginning)
Update the configuration docs as well
> BE: Default to no CSRF cookie domain

- Caddyfile
- frontend/svelte.config.js
- stories/package-lock.json
- stories/package.json
- stories/svelte.config.js
When serving the static frontend through adapter-node and Caddy, we don't receive a CSP from "upstream", i.e., the node server that Caddy forwards requests from as a reverse proxy. This means that we fall back to an extremely strict CSP in the HTTP header.
The problem is that the script nonces are part of the HTML returned itself. CSPs can't go from strict to less-strict, so having a strict CSP header means that the less-strict CSP meta tags will be ignored. This leads to the frontend not running any JavaScript on prerendered pages.
The solution is to revert part of the recent Caddy CSP changes, but only for when no CSP header is returned from adapter-node. In that case we fall back to a less strict CSP. This is not ideal. Adapter-node could return to us a full set of CSP headers as part …
> Fall back to less strict CSP header when serving static frontend

- Caddyfile
As encouraged by https://developer.mozilla.org/en-US/observatory/analyze
- Set HSTS to 6 months
- Set X-Content-Type-Options nosniff
> Revproxy: Tighten header security

- backend/mypy/stubs/rest_framework/test.pyi
- backend/poetry.lock
- backend/projectify/settings/base.py
- backend/projectify/user/test/views/test_auth.py
- backend/projectify/user/views/auth.py
- backend/pyproject.toml
- frontend/src/lib/utils/cookie.ts
Some users might not be able to pass CSRF checks because of a previously set CSRF tokens. This branch introduces the following changes:
- Add a CSRF check failure test case.
- Prefer the last cookie found in getCookie(). I assume this chooses the most recently inserted cookie, although that's not guaranteed to be true.
- Make cookie samesite policies strict, since we serve everything through the same domain now.
- Remove some stray print()s
> Mitigate stale domain CSRF issues

- backend/projectify/settings/production.py
We switched to the EU mailgun server, but forgot to update the API URL in the settings.
Thankfully, django-anymail's docs had a solution ready
https://anymail.dev/en/stable/esps/mailgun/#settings
> BE: Fix broken mailgun URL

- backend/flake.nix
- backend/poetry.lock
- backend/projectify/settings/base.py
- backend/pyproject.toml
Install django-markdownify. This commit is based off of commit e669acf1a9899083b4446504f014c18e8c699691
This fixes the following Nix build issue caused by poetry not supporting the new pyproject.toml syntax:
```
python3.12-markdown>   configuration error: `project.license` must be valid exactly by one
python3.12-markdown>       - keys:
python3.12-markdown>           'file': {type: string}
python3.12-markdown>         required: ['file']
python3.12-markdown>       - keys:
python3.12-markdown>           'text': {type: string}
python3.12-markdown>         required: ['text']
python3.12-markdown>   DESCRIPTION:
python3.12-markdown>       `Project license <https://peps.python.org/pep-0621/#license>`_.
python3.12-markdown>   GIVEN VALUE:
python3.12-markdown>       "BSD-3-Clause"
```
The solution …
> BE: Install django-markdownify

- frontend/src/lib/utils/keyboard.ts
It was not possible to input some key on dashboard page. For example, when you type "l" at the text field to create a new label, the browser moves its focus to the task on the left side.
Avoid executing an short cut event if the browser is focused on INPUT element
> FE: Fix dashboard page shortcut key function
